using FluentAssertions;
using Xunit;
using Xunit.Abstractions;
using _2017;

namespace _2017Test
{
	public class Day7Test
	{
		private readonly ITestOutputHelper _output;

		public Day7Test(ITestOutputHelper output)
		{
			_output = output;
		}

		[Fact]
		public void Example1()
		{
			var target = new Day7();
			target.AddProgram("pbga (66)");
			target.AddProgram("xhth (57)");
			target.AddProgram("ebii (61)");
			target.AddProgram("havc (66)");
			target.AddProgram("ktlj (57)");
			target.AddProgram("fwft (72) -> ktlj, cntj, xhth");
			target.AddProgram("qoyq (66)");
			target.AddProgram("padx (45) -> pbga, havc, qoyq");
			target.AddProgram("tknk (41) -> ugml, padx, fwft");
			target.AddProgram("jptl (61)");
			target.AddProgram("ugml (68) -> gyxo, ebii, jptl");
			target.AddProgram("gyxo (61)");
			target.AddProgram("cntj (57)");
			;

			var result = target.CalculateBottomProgram();

			result.Should().Be("tknk");
		}

		[Fact]
		public void ShouldSolve()
		{
			var target = new Day7();
			target.AddProgram("xcpuy (20)");
			target.AddProgram("prxlb (35)");
			target.AddProgram("yibbu (160)");
			target.AddProgram("pgvds (134) -> manpd, vkikri");
			target.AddProgram("kzvbkr (24)");
			target.AddProgram("bwhjal (68)");
			target.AddProgram("vozygf (134) -> fzyftv, yiozhnf, hxscfiv");
			target.AddProgram("ynzpsk (17)");
			target.AddProgram("uwmbh (34)");
			target.AddProgram("juqrwwm (98) -> bhtoyru, ulacz, enkufi");
			target.AddProgram("ctjnwq (22) -> tasqwda, qfybq");
			target.AddProgram("ibjoxjo (175) -> ubhsnqw, icjmhii, lmvfuql, wrnmwy");
			target.AddProgram("puxlsjo (26) -> gyveijp, nikvfs");
			target.AddProgram("aaeeqh (68) -> nmyem, fserz");
			target.AddProgram("sfxng (33)");
			target.AddProgram("uvhyl (23)");
			target.AddProgram("gtkkx (91)");
			target.AddProgram("ovkpba (352)");
			target.AddProgram("dkjfjwe (146) -> ehnlfa, sxzwplf");
			target.AddProgram("fjklelc (83) -> pjkrhl, yshith");
			target.AddProgram("gzmejde (318) -> eghfd, oxcou");
			target.AddProgram("suhso (32)");
			target.AddProgram("cnvir (249) -> zghut, fjrwy");
			target.AddProgram("rgzch (92)");
			target.AddProgram("cqnlk (229) -> lpvqp, pdowqq");
			target.AddProgram("insxh (186)");
			target.AddProgram("qutgb (83)");
			target.AddProgram("byhatd (1716) -> zeenwpx, tqyte, nrgwyzb");
			target.AddProgram("lfzthdo (85)");
			target.AddProgram("aftndu (11) -> xckzcq, cymvz, oblhfhz");
			target.AddProgram("nxkpw (34)");
			target.AddProgram("btyotwv (139) -> asbiye, nmvqwi, swwtm, ctytwcc");
			target.AddProgram("zbwysvr (1226) -> ckdwk, bjzlgik, lbajhe, lnoihzx");
			target.AddProgram("jqwhun (39)");
			target.AddProgram("ohyrn (68)");
			target.AddProgram("gwvhjfe (13)");
			target.AddProgram("fczix (226) -> yvdilfo, cprsra");
			target.AddProgram("acrly (75)");
			target.AddProgram("lfoiu (13)");
			target.AddProgram("fxptqn (242) -> srqrs, mxgqn");
			target.AddProgram("emcjby (96)");
			target.AddProgram("ztpysan (63)");
			target.AddProgram("bfioj (56)");
			target.AddProgram("ovtoke (56)");
			target.AddProgram("pgkiqa (75)");
			target.AddProgram("muesucc (50)");
			target.AddProgram("hlyodf (27)");
			target.AddProgram("drvxvk (102) -> bmzlp, elpfsya");
			target.AddProgram("cnhsgdv (264)");
			target.AddProgram("ioexd (52) -> shfyok, xcwlym");
			target.AddProgram("juvwqt (63)");
			target.AddProgram("gaspe (54)");
			target.AddProgram("qkqyelb (253) -> ehravmh, qzqtysl");
			target.AddProgram("hekihe (18)");
			target.AddProgram("jljwoo (171) -> uqajm, dgyjldr");
			target.AddProgram("yornm (149) -> nniqh, gqcmcc");
			target.AddProgram("tqqldx (74)");
			target.AddProgram("bxqdudx (195) -> dyacjh, nsecr, unfpyg");
			target.AddProgram("fqbovid (93)");
			target.AddProgram("yzexxy (68)");
			target.AddProgram("xfwgll (8)");
			target.AddProgram("omytneg (1366) -> hmvin, eppzprf, zrioi, sdlcqtb");
			target.AddProgram("dgjqciq (24)");
			target.AddProgram("wxtrq (340) -> eolll, wawkzh");
			target.AddProgram("ctdghk (57)");
			target.AddProgram("oninxl (46)");
			target.AddProgram("kxjnq (92)");
			target.AddProgram("klccwcn (22)");
			target.AddProgram("ktyyedq (61)");
			target.AddProgram("tqyte (225) -> xpzymh, wdyxx");
			target.AddProgram("ajmtxv (267) -> sjmci, yhdjwd");
			target.AddProgram("uraugcn (73)");
			target.AddProgram("mztwrvf (34) -> kmvcjir, cgwnor");
			target.AddProgram("kozlia (37)");
			target.AddProgram("pbxguu (28)");
			target.AddProgram("ktooxbh (74)");
			target.AddProgram("qjcsn (65)");
			target.AddProgram("pvvbn (8732) -> adyni, dvltfhm, luerna");
			target.AddProgram("avroyn (58)");
			target.AddProgram("mdkfx (54)");
			target.AddProgram("fbdrf (80)");
			target.AddProgram("evqfv (62)");
			target.AddProgram("enkufi (62) -> vurdsd, srpcy, dihezs, xzcix");
			target.AddProgram("lxngrgu (56)");
			target.AddProgram("xyhoa (33)");
			target.AddProgram("jcqgj (46) -> nxqswd, lznju, kohici");
			target.AddProgram("ysnwjl (29)");
			target.AddProgram("szcqd (260) -> gpzqcqk, tnngnq");
			target.AddProgram("wlcjt (298)");
			target.AddProgram("rjhws (97)");
			target.AddProgram("srqrs (46)");
			target.AddProgram("xnfstk (61)");
			target.AddProgram("ixukpw (77)");
			target.AddProgram("cujtqk (74)");
			target.AddProgram("nfvliuy (97)");
			target.AddProgram("iondfqm (45)");
			target.AddProgram("vzlvim (10)");
			target.AddProgram("wijfihq (156) -> zauue, mgqziu, egrlfh");
			target.AddProgram("iyosp (88) -> gcpipz, scsxe");
			target.AddProgram("bdohoaa (18440) -> lxjbzu, ppsnn, hatfl");
			target.AddProgram("lrxyqgr (106) -> phppbj, tbure, sspayll");
			target.AddProgram("ffejzo (70) -> lcourm, rdfab");
			target.AddProgram("wawkzh (16)");
			target.AddProgram("mnvlfcf (132) -> icmmx, hsnsncv, bsmryo");
			target.AddProgram("kbpnl (10)");
			target.AddProgram("pnqrgfk (1707) -> msekejl, aaroa, tfregkr");
			target.AddProgram("gjmkox (57)");
			target.AddProgram("fufzi (191) -> evhgkft, kzroqbi");
			target.AddProgram("uoyzsdf (20)");
			target.AddProgram("otxroc (56)");
			target.AddProgram("gtmcr (578) -> svsgzi, pnmkl, owsvc");
			target.AddProgram("orbwii (77)");
			target.AddProgram("mkqtej (81)");
			target.AddProgram("nmpxqi (205) -> prspd, uaguc");
			target.AddProgram("ltseugc (37)");
			target.AddProgram("kfyaw (76)");
			target.AddProgram("dgyjldr (62)");
			target.AddProgram("rsvudoc (1348) -> zwvtdhw, gpvlztd, njvsnz");
			target.AddProgram("mxgqn (46)");
			target.AddProgram("yjbjy (98)");
			target.AddProgram("ftrzswp (84)");
			target.AddProgram("nzakpnw (50) -> gjjgkga, bvgct, pzbgf");
			target.AddProgram("iufypzm (58)");
			target.AddProgram("utizol (25)");
			target.AddProgram("bwkwgf (206) -> huhxf, txzlem, rlfbix, itzdby");
			target.AddProgram("ydehaq (67)");
			target.AddProgram("ovuqg (22)");
			target.AddProgram("scsxe (49)");
			target.AddProgram("jfuzgpw (34)");
			target.AddProgram("hdtxgb (22)");
			target.AddProgram("snluaf (45)");
			target.AddProgram("dhpviei (25)");
			target.AddProgram("kfxcot (182) -> hxqik, lkstwl, vqumdju");
			target.AddProgram("zgcfeda (8)");
			target.AddProgram("fixsej (22)");
			target.AddProgram("cyrqkl (86)");
			target.AddProgram("risguql (97)");
			target.AddProgram("fvyiwup (165) -> hdtxgb, ovuqg, klccwcn, fixsej");
			target.AddProgram("mzlub (83)");
			target.AddProgram("lhcinxf (58)");
			target.AddProgram("xjszzfe (92)");
			target.AddProgram("uqqclia (4793) -> gtmcr, ohitm, ashxpav");
			target.AddProgram("mbcpufw (85)");
			target.AddProgram("urxzo (145) -> ntqdxv, nxnjrzj, fcbeagx, aqxdf");
			target.AddProgram("qpycn (544) -> yornm, iiygchg, vpvcum, plbmu, bxqdudx, twfzzyt");
			target.AddProgram("basiy (133) -> qifofxk, qutgb");
			target.AddProgram("dvpay (74)");
			target.AddProgram("kridw (175) -> edmfm, jrigbij");
			target.AddProgram("tmbkt (94)");
			target.AddProgram("zibll (188)");
			target.AddProgram("mhdauqb (89)");
			target.AddProgram("bilxm (96)");
			target.AddProgram("qmgot (69)");
			target.AddProgram("hxscfiv (93)");
			target.AddProgram("soixton (66)");
			target.AddProgram("lbajhe (180) -> fausgp, zkeep");
			target.AddProgram("edbemy (286)");
			target.AddProgram("mwkct (11)");
			target.AddProgram("iwkqae (35)");
			target.AddProgram("ilbcji (205) -> ctxwkkt, utizol");
			target.AddProgram("wusxwq (1078) -> npzlka, wxsvnj, kirvox, pqguzw, tecducv");
			target.AddProgram("xqssuna (10)");
			target.AddProgram("cslrgbh (64)");
			target.AddProgram("aubapo (11)");
			target.AddProgram("twfzzyt (175) -> rdomi, pcwawh");
			target.AddProgram("hhrvet (301) -> mskxqki, jwtzgjf");
			target.AddProgram("iarbj (93)");
			target.AddProgram("uhukwcq (151) -> pnncrgq, yuepo");
			target.AddProgram("rnkvgzf (78)");
			target.AddProgram("usevrmp (96)");
			target.AddProgram("zdcdmle (97)");
			target.AddProgram("nwhunwf (88) -> ygidtwv, lrxzg, ifluvxj, soixton");
			target.AddProgram("qfybq (95)");
			target.AddProgram("ahrfh (2040) -> yyfrmb, actlu");
			target.AddProgram("zgvpy (200) -> nxkpw, hhpysjd");
			target.AddProgram("ahnkcy (83)");
			target.AddProgram("woqvn (54)");
			target.AddProgram("ktfbjoo (90) -> jgsydq, yjbjy");
			target.AddProgram("usfzaf (25)");
			target.AddProgram("iaini (32)");
			target.AddProgram("jarvx (188) -> jjlsy, nrywfm");
			target.AddProgram("fuyldc (70)");
			target.AddProgram("cdovdt (410)");
			target.AddProgram("eqxce (23) -> qtatze, wwoye, qkseme, yrtlizo, kridw, birvaha");
			target.AddProgram("vkgqysh (47) -> cpmxvjn, aebhvbk, epubm");
			target.AddProgram("xppkv (249) -> uasrsi, qfqkz, rkznog");
			target.AddProgram("kbmrrew (38)");
			target.AddProgram("tkhgo (59)");
			target.AddProgram("cebdo (17)");
			target.AddProgram("holuib (302) -> usfzaf, oustcqz");
			target.AddProgram("obqblrl (83)");
			target.AddProgram("crxji (97)");
			target.AddProgram("lqsgphu (91)");
			target.AddProgram("gldorrf (198) -> byymvpo, ulkpoko");
			target.AddProgram("oujtz (69) -> cyrqkl, vjcexcx, wuztvge");
			target.AddProgram("ulkpoko (68)");
			target.AddProgram("pwdziu (253) -> nwhma, igbhn, ckyoc, kfvur");
			target.AddProgram("zxqmj (20)");
			target.AddProgram("iartkgt (91)");
			target.AddProgram("hcorylb (97)");
			target.AddProgram("nkfpci (87)");
			target.AddProgram("qdmqsrh (80)");
			target.AddProgram("fkfyeej (299)");
			target.AddProgram("jkfce (7)");
			target.AddProgram("rwkuzs (29)");
			target.AddProgram("fzqdsv (38) -> yptyp, wohpoh");
			target.AddProgram("aqxdf (16)");
			target.AddProgram("bvdnvep (18)");
			target.AddProgram("nxnjrzj (16)");
			target.AddProgram("csdrrx (323) -> rwkuzs, jbdtgk");
			target.AddProgram("tubcr (46)");
			target.AddProgram("ebootd (83)");
			target.AddProgram("lkuelr (62)");
			target.AddProgram("prspd (25)");
			target.AddProgram("eooiuq (54) -> qiqjmmi, gperhh, qanpeab, bwkwgf, jgmyc");
			target.AddProgram("zhpmkq (89)");
			target.AddProgram("cexrf (72)");
			target.AddProgram("gzilup (14)");
			target.AddProgram("rvzkv (70) -> wgsgyv, neafgd, oseqshg");
			target.AddProgram("aqdjk (80)");
			target.AddProgram("owsvc (433)");
			target.AddProgram("vkybxfk (56)");
			target.AddProgram("dwnys (55)");
			target.AddProgram("iiktsrr (17)");
			target.AddProgram("tfzsqj (89) -> pqknhsq, fhbjovx, jbaxm, pvnfa, eqxce, hbmzilw, hyxxm");
			target.AddProgram("pnmkl (325) -> rhyglf, meybf");
			target.AddProgram("bwntinc (13)");
			target.AddProgram("dbrxe (69)");
			target.AddProgram("nrsrwb (45)");
			target.AddProgram("vinbva (278) -> jpjezb, zfswj");
			target.AddProgram("ojkhavf (1465) -> siujrb, igxzggb");
			target.AddProgram("kuusoe (396) -> gxcwynf, mxvhj, wijfihq");
			target.AddProgram("vjmzqbb (89)");
			target.AddProgram("jggzx (20)");
			target.AddProgram("liida (77)");
			target.AddProgram("wlxwq (70)");
			target.AddProgram("izjeb (105) -> lduim, hgegrz, veegvvc, pvzeznc");
			target.AddProgram("akxtfh (57)");
			target.AddProgram("avflv (46)");
			target.AddProgram("qkmqmg (40)");
			target.AddProgram("eflcxi (21)");
			target.AddProgram("kexdopt (21)");
			target.AddProgram("wuvctps (43)");
			target.AddProgram("tpjuj (24) -> fnvptes, bjtlzzh, tyajj, izjeb, kfxcot, wvhdyg");
			target.AddProgram("jvsmwee (88)");
			target.AddProgram("gqlnaho (84) -> tlfaxub, xjszzfe");
			target.AddProgram("hazyoke (40)");
			target.AddProgram("fapkonf (3295) -> hmlvv, xppkv, ezwitpp");
			target.AddProgram("cjinsf (80) -> wwyuko, renqhyi");
			target.AddProgram("bvoqpkb (18)");
			target.AddProgram("wdyxx (47)");
			target.AddProgram("tlnffr (58)");
			target.AddProgram("dlodc (70) -> zhpmkq, xbiuhd");
			target.AddProgram("lpjbjju (38)");
			target.AddProgram("ifluvxj (66)");
			target.AddProgram("rxerq (168) -> uoyzsdf, seyiftq, ydfmxw, ezgvb");
			target.AddProgram("nplbgrk (59)");
			target.AddProgram("cyjcaht (13)");
			target.AddProgram("hxeia (271) -> fzvllyz, hidmpw");
			target.AddProgram("wgjrzd (93) -> touatc, grbpi, lclxb, grqtsex");
			target.AddProgram("tkoxc (1050) -> pmafsug, jbaztvm, rsvudoc, kixlvf, ogjeuhl, tthmac, qpycn");
			target.AddProgram("yuzwdix (43)");
			target.AddProgram("vtewtb (85) -> thablkl, hyywt, baljt, insvmt");
			target.AddProgram("dihezs (91)");
			target.AddProgram("jorbfl (181) -> uvhyl, bqjypo");
			target.AddProgram("rkznog (9) -> civhlqc, xytulz");
			target.AddProgram("bxdbijl (63)");
			target.AddProgram("nkywqaj (40)");
			target.AddProgram("oppmeig (60) -> yqhss, suupi");
			target.AddProgram("dkjsfxs (59)");
			target.AddProgram("igxzggb (42)");
			target.AddProgram("drjmjug (428) -> goiwg, sbogacc, jdvxawc, wlczi, vinbva");
			target.AddProgram("lclxb (80)");
			target.AddProgram("bjdlb (50) -> yonojr, fwubo");
			target.AddProgram("ckakkja (38) -> fqbovid, siulcz, bapvqa, pwajo");
			target.AddProgram("igbhn (40)");
			target.AddProgram("cwwpev (17)");
			target.AddProgram("maqzwn (37)");
			target.AddProgram("rhtamt (85)");
			target.AddProgram("ezwitpp (123) -> aftndu, urxzo, qchxbon");
			target.AddProgram("edaslb (190) -> robfhmz, qbqjz");
			target.AddProgram("crlkolg (36)");
			target.AddProgram("izjppbx (1108) -> qzvrq, cgnewz, zbwysvr, xkghfhn, ugujla, nwfykuw");
			target.AddProgram("aebhvbk (92)");
			target.AddProgram("ohjax (56)");
			target.AddProgram("ozvtq (254) -> zjchuge, zxqmj, xcpuy");
			target.AddProgram("fuvpi (83)");
			target.AddProgram("gdneruv (2040) -> srgfuk, btyotwv, butfc");
			target.AddProgram("maubg (85) -> cnxyhg, mpgge, uyfzha");
			target.AddProgram("ckgotfs (94) -> bilxm, emcjby");
			target.AddProgram("vtqpilo (75)");
			target.AddProgram("tfjadw (41)");
			target.AddProgram("paqbnl (39)");
			target.AddProgram("mudup (87)");
			target.AddProgram("zgxczmq (98)");
			target.AddProgram("egrlfh (20)");
			target.AddProgram("icgwqn (84)");
			target.AddProgram("lxouzag (61)");
			target.AddProgram("qbfsj (60)");
			target.AddProgram("fbnbt (5262) -> lcmek, aflzz, rqgccu, vxfpzku, yvixrl, ojkhavf");
			target.AddProgram("nvkqru (139) -> sdqzod, raucx");
			target.AddProgram("gnrij (65)");
			target.AddProgram("kwtghnf (25)");
			target.AddProgram("azxoyif (1368) -> dkohgp, irgkfsa, plysamb");
			target.AddProgram("yrmqu (14)");
			target.AddProgram("xcwlym (14)");
			target.AddProgram("yvixrl (7) -> stguc, dfywfie, ialmhy, pkpgu, nzakpnw, ompeys");
			target.AddProgram("wwyuko (52)");
			target.AddProgram("cujdv (18)");
			target.AddProgram("lxuiwb (201) -> ubnap, qbdisnk, urqoabs, oepwc");
			target.AddProgram("touatc (80)");
			target.AddProgram("ubllrlw (8)");
			target.AddProgram("idqaxgi (78)");
			target.AddProgram("yxotxz (42)");
			target.AddProgram("pnncrgq (51)");
			target.AddProgram("qnpzxal (75)");
			target.AddProgram("bhfeafe (91) -> pfgsvs, ruzgpq");
			target.AddProgram("nsdver (97)");
			target.AddProgram("uqajm (62)");
			target.AddProgram("cxapyp (261) -> aodkqlr, lmxvhwl, ralmgdq");
			target.AddProgram("uzqnl (220) -> xyhoa, sfxng");
			target.AddProgram("yeimwk (56)");
			target.AddProgram("oblhfhz (66)");
			target.AddProgram("ppsnn (7698) -> hhrvet, ajmtxv, wubrts, nyjgkav, lfvih, kyrookv");
			target.AddProgram("oarmggv (14)");
			target.AddProgram("zkqxpbq (97)");
			target.AddProgram("lnreval (98)");
			target.AddProgram("zvbnb (28)");
			target.AddProgram("kpxrk (45)");
			target.AddProgram("gfhuv (40)");
			target.AddProgram("bqjypo (23)");
			target.AddProgram("gghqilu (186) -> sxxnze, paioxf, gjmbm, kwtghnf");
			target.AddProgram("lvsqvdi (13)");
			target.AddProgram("lvuah (66)");
			target.AddProgram("mkuernu (60)");
			target.AddProgram("zvqyr (36)");
			target.AddProgram("sspayll (39)");
			target.AddProgram("twzglew (14)");
			target.AddProgram("rnvvg (456) -> dkjfjwe, pbeez, cjinsf");
			target.AddProgram("hlxlrjq (48) -> dzrsha, stkvqy");
			target.AddProgram("lhypfq (51)");
			target.AddProgram("mdwiktj (15)");
			target.AddProgram("mytnwmk (58)");
			target.AddProgram("bvgct (69)");
			target.AddProgram("yedwosl (18)");
			target.AddProgram("jvneo (51)");
			target.AddProgram("brdpdm (34)");
			target.AddProgram("apkfhsb (36) -> mwknwxh, mqrvu");
			target.AddProgram("tgvzdov (40) -> pubgkhb, angyt");
			target.AddProgram("rppgdnf (11) -> tbkxpdv, vugudp, etyqg, zlbfpnu");
			target.AddProgram("ehefb (2158) -> akxtfh, uxqlce");
			target.AddProgram("owsoywa (99)");
			target.AddProgram("swtks (14)");
			target.AddProgram("qiqjmmi (10) -> hgznhq, zknngyu, lkhvhui, tcmexa, edaslb, gzmejde");
			target.AddProgram("nebitb (19)");
			target.AddProgram("hkmaxza (221)");
			target.AddProgram("hpaeg (54) -> lvqkp, xjbmdc, solooh");
			target.AddProgram("avjfqex (74)");
			target.AddProgram("lmntml (74)");
			target.AddProgram("sfpveq (38)");
			target.AddProgram("svsgzi (45) -> nsdver, xexswl, oidmfs, gwlrdbk");
			target.AddProgram("kbpklq (173) -> oajdkzc, lxouzag");
			target.AddProgram("vlbkhb (93)");
			target.AddProgram("tjjkgb (69)");
			target.AddProgram("tbfce (5) -> vozygf, mjmskc, rludm, wgjrzd, pwdziu");
			target.AddProgram("nwhma (40)");
			target.AddProgram("gabbp (70)");
			target.AddProgram("beyphy (221) -> cwfgzrp, ojnrf");
			target.AddProgram("kqjfnb (91) -> tlnffr, avroyn, mytnwmk, zamoi");
			target.AddProgram("lfpwycg (209) -> qiniyf, vdtdpz");
			target.AddProgram("zyqkcmb (130) -> ynbruov, dqvygcd, gzilup, oarmggv");
			target.AddProgram("uaguc (25)");
			target.AddProgram("eatoyd (91)");
			target.AddProgram("taizyha (45)");
			target.AddProgram("uembuig (39)");
			target.AddProgram("cpmxvjn (92)");
			target.AddProgram("bfaak (89)");
			target.AddProgram("bkrctx (84) -> usevrmp, bkrbfap, weaier");
			target.AddProgram("eppzprf (120) -> zvbnb, pbxguu");
			target.AddProgram("nrgwyzb (263) -> eunfszw, aijmghs");
			target.AddProgram("qucnu (225)");
			target.AddProgram("igblzk (97)");
			target.AddProgram("hgegrz (53)");
			target.AddProgram("uaknxb (99)");
			target.AddProgram("lnoihzx (43) -> qkhudy, zdseqzi, ydehaq");
			target.AddProgram("dejsmq (41)");
			target.AddProgram("plbmu (107) -> rcaajf, qdmqsrh");
			target.AddProgram("naseaj (61)");
			target.AddProgram("jdvxawc (26) -> kfyaw, kglxbse, ukkmfh, jyoevqm");
			target.AddProgram("sierb (113) -> asihmc, iaini, wepwf");
			target.AddProgram("kglxbse (76)");
			target.AddProgram("sigya (98)");
			target.AddProgram("manpd (82)");
			target.AddProgram("rodegh (88)");
			target.AddProgram("lhauud (220) -> zlaxh, eqtmes");
			target.AddProgram("sspng (199) -> dkcrll, mnvfi");
			target.AddProgram("tntib (246) -> ldypun, aubapo");
			target.AddProgram("vjstu (84)");
			target.AddProgram("rjkumo (97)");
			target.AddProgram("qqncuk (77)");
			target.AddProgram("suyzrmf (155) -> ybfyes, cndqzdm");
			target.AddProgram("kyrookv (181) -> mdxcp, zdcdmle");
			target.AddProgram("viubix (10)");
			target.AddProgram("epblwo (314) -> ysnwjl, mryuhsl");
			target.AddProgram("itluk (97)");
			target.AddProgram("ovuesou (85)");
			target.AddProgram("jqeabja (81) -> luulwx, jjanr");
			target.AddProgram("zefoig (27)");
			target.AddProgram("blbzqf (209) -> vnlcfxn, yqeuhw");
			target.AddProgram("hkfgksw (22)");
			target.AddProgram("pbeez (64) -> qbfsj, xprrajl");
			target.AddProgram("tbure (39)");
			target.AddProgram("hobnerj (89)");
			target.AddProgram("bonoob (78)");
			target.AddProgram("qylxl (277) -> ttiaks, pijlcc");
			target.AddProgram("jgsydq (98)");
			target.AddProgram("hafgurf (95)");
			target.AddProgram("nrvqpd (58)");
			target.AddProgram("mqrvu (44)");
			target.AddProgram("srgfuk (109) -> hewzwp, ienee, uwmbh");
			target.AddProgram("ldypun (11)");
			target.AddProgram("pkivl (217) -> kdwzsz, dejsmq");
			target.AddProgram("ywacbmq (87)");
			target.AddProgram("slsrzl (60) -> fqskwj, lhypfq, jvneo, mwbpro");
			target.AddProgram("icqkc (13)");
			target.AddProgram("edvqwvm (60)");
			target.AddProgram("ivrnod (42)");
			target.AddProgram("xpjksm (46)");
			target.AddProgram("pfgsvs (84)");
			target.AddProgram("xkghfhn (1524) -> hdlfpj, deqcnp, iomxv");
			target.AddProgram("euqxp (77)");
			target.AddProgram("hdkvbzv (50) -> aqubpi, twogxyg, vcrsnrf, xezse");
			target.AddProgram("cixqrb (62)");
			target.AddProgram("ofxag (36) -> flyxei, jpwtw");
			target.AddProgram("yypfse (46)");
			target.AddProgram("hgznhq (302) -> tkqdly, kexdopt");
			target.AddProgram("xgdolgm (59)");
			target.AddProgram("pzbgf (69)");
			target.AddProgram("uymwt (24)");
			target.AddProgram("zwiidh (85)");
			target.AddProgram("ubnap (21)");
			target.AddProgram("tkdsfz (17)");
			target.AddProgram("yfwki (55) -> jqgjdku, jbsxc, lcsqza");
			target.AddProgram("yonojr (53)");
			target.AddProgram("geavik (8)");
			target.AddProgram("luerna (10160) -> fpekhb, hyolftw, rnvvg");
			target.AddProgram("yxccn (86) -> dknly, xtbdj");
			target.AddProgram("povsm (58)");
			target.AddProgram("eolll (16)");
			target.AddProgram("syfccrr (92)");
			target.AddProgram("lbgwc (24)");
			target.AddProgram("rkevnnd (81)");
			target.AddProgram("wqtku (66)");
			target.AddProgram("uspjc (84)");
			target.AddProgram("iiygchg (151) -> cwehc, cwkdjn, pppsd, ydnsnh");
			target.AddProgram("mzdxg (51) -> yqdsxvc, bxdbijl");
			target.AddProgram("bvfee (35)");
			target.AddProgram("kuhybd (73)");
			target.AddProgram("flwhrzk (31)");
			target.AddProgram("djkaku (44)");
			target.AddProgram("oaefi (9) -> yigwd, nldvtr");
			target.AddProgram("xqsufx (61)");
			target.AddProgram("kyfcsou (68)");
			target.AddProgram("ienee (34)");
			target.AddProgram("ojnrf (35)");
			target.AddProgram("jwtzgjf (37)");
			target.AddProgram("jajbpsk (39)");
			target.AddProgram("wxsvnj (205) -> rabdvok, vrbjw");
			target.AddProgram("mwknwxh (44)");
			target.AddProgram("pijlcc (9)");
			target.AddProgram("ulacz (412) -> ghzvdod, jkfce");
			target.AddProgram("axfvokp (35)");
			target.AddProgram("ugujla (78) -> fybpzfy, uiyxk, selfpoj, fdurqvg, kdsscve, jarvx");
			target.AddProgram("uvjevu (45)");
			target.AddProgram("evmkzjr (8)");
			target.AddProgram("mdfjh (58)");
			target.AddProgram("mqafr (88)");
			target.AddProgram("rdbbda (73)");
			target.AddProgram("jywye (68)");
			target.AddProgram("nvlpgon (88)");
			target.AddProgram("qqqvdsu (160) -> cyjcaht, bwntinc, hhrdosf, lvsqvdi");
			target.AddProgram("bcwbp (43)");
			target.AddProgram("jpjezb (26)");
			target.AddProgram("ujhkl (13)");
			target.AddProgram("tjwodb (63)");
			target.AddProgram("etyqg (71)");
			target.AddProgram("xrppd (57)");
			target.AddProgram("ppstt (61)");
			target.AddProgram("pwmqpk (62)");
			target.AddProgram("xpzymh (47)");
			target.AddProgram("stkvqy (78)");
			target.AddProgram("mljlpfo (90) -> gnrij, lalblzp");
			target.AddProgram("byymvpo (68)");
			target.AddProgram("zauue (20)");
			target.AddProgram("cqdyyoo (401)");
			target.AddProgram("wwoye (211) -> ojhbiv, cixqrb");
			target.AddProgram("pjkrhl (56)");
			target.AddProgram("rpiefl (120) -> cjnkge, xqmhigw, ugeucjn, brdpdm");
			target.AddProgram("pvzeznc (53)");
			target.AddProgram("yigwd (84)");
			target.AddProgram("bbiczh (13)");
			target.AddProgram("vdgvmd (18)");
			target.AddProgram("qchxbon (109) -> muesucc, vvukaca");
			target.AddProgram("btpbnr (31)");
			target.AddProgram("wuztvge (86)");
			target.AddProgram("iegjd (275) -> geavik, zgcfeda");
			target.AddProgram("oydwkrv (69)");
			target.AddProgram("dhmhbw (50)");
			target.AddProgram("krhkthl (52)");
			target.AddProgram("umkwllw (7)");
			target.AddProgram("amgrlkr (75)");
			target.AddProgram("sfztpf (84)");
			target.AddProgram("glfoc (15)");
			target.AddProgram("xprrajl (60)");
			target.AddProgram("ralmgdq (91) -> bmcsya, lfzthdo");
			target.AddProgram("jqvjr (47) -> adzvlgk, fdvgk, lnttud, aspoy");
			target.AddProgram("ebeitz (1424) -> utdhy, hfzyzt, cidfent, ctjnwq, fjkjmhd");
			target.AddProgram("ihqfqm (365) -> zixgz, glfoc, ieabomm");
			target.AddProgram("dzrsha (78)");
			target.AddProgram("cwfgzrp (35)");
			target.AddProgram("mskxqki (37)");
			target.AddProgram("ywhxoi (94)");
			target.AddProgram("lmavxq (75) -> idqaxgi, bonoob");
			target.AddProgram("mpmmos (56)");
			target.AddProgram("wklmecc (66) -> amgrlkr, vtqpilo, nnnfykw");
			target.AddProgram("oajdkzc (61)");
			target.AddProgram("izkhkai (45)");
			target.AddProgram("mcxti (62)");
			target.AddProgram("lztme (46)");
			target.AddProgram("mxvhj (216)");
			target.AddProgram("ljqmwwg (41)");
			target.AddProgram("dhrun (37)");
			target.AddProgram("tkgkl (40)");
			target.AddProgram("ifvkdba (52) -> ibuilzl, yalugkr, vxbio, pgkiqa");
			target.AddProgram("hgzsxur (10) -> iwczlkt, qmgot, tjjkgb, umjdo");
			target.AddProgram("jjanr (57)");
			target.AddProgram("cjnab (72)");
			target.AddProgram("yffnz (1004) -> smvodeb, ztruf, apkfhsb");
			target.AddProgram("rmbzvq (19)");
			target.AddProgram("wvaketk (46)");
			target.AddProgram("qjhdxdr (74)");
			target.AddProgram("thablkl (18)");
			target.AddProgram("chrzza (66) -> pnfwlas, igbqenq, hmytpw, nwhunwf");
			target.AddProgram("vhusoux (1834) -> slsrzl, cnhsgdv, bzvqqp");
			target.AddProgram("qcdsvv (82)");
			target.AddProgram("pzfdzb (87)");
			target.AddProgram("dxlttzs (70)");
			target.AddProgram("pvnfa (503) -> rwjlopt, aqcwqy, ilbcji, suyzrmf, nmpxqi, ibjoxjo");
			target.AddProgram("utdhy (100) -> owkjav, vkybxfk");
			target.AddProgram("aqcwqy (101) -> httgiox, orbwii");
			target.AddProgram("qiveb (197) -> gpqcq, evpav, btpbnr");
			target.AddProgram("hbmzilw (1829) -> wnaykx, ncrotbi, jywye");
			target.AddProgram("qklhqlf (46)");
			target.AddProgram("shyxe (93)");
			target.AddProgram("gounu (145) -> azvltq, jrquxee");
			target.AddProgram("kbehv (62) -> dbbsyeo, jotnlgm, igqzqiy, uhukwcq, zhallzk, fvyiwup, wgkxy");
			target.AddProgram("rtwwdrh (417) -> wbflq, sierb, cawvue");
			target.AddProgram("qlesgoz (185) -> pwlpeu, rchqa");
			target.AddProgram("rwjlopt (11) -> xqsufx, bjwgltq, naseaj, zjioec");
			target.AddProgram("jjlsy (83)");
			target.AddProgram("mryuhsl (29)");
			target.AddProgram("ehravmh (37)");
			target.AddProgram("xjpuoil (31)");
			target.AddProgram("jbwoozn (111) -> otxroc, bfioj");
			target.AddProgram("wubrts (330) -> jjsbd, mdwiktj, qnuusbq");
			target.AddProgram("fxnbfjk (8)");
			target.AddProgram("luufi (53)");
			target.AddProgram("cjnkge (34)");
			target.AddProgram("xzjbmpu (323) -> zefoig, zljgpq");
			target.AddProgram("ijajh (55)");
			target.AddProgram("pmebb (42)");
			target.AddProgram("jerwsi (80)");
			target.AddProgram("lmxvhwl (175) -> azbjh, wuvctps");
			target.AddProgram("pqguzw (181) -> kqtye, xpjksm, oninxl");
			target.AddProgram("qqkctf (121) -> zouklk, busosd");
			target.AddProgram("rchqa (98)");
			target.AddProgram("ojhbiv (62)");
			target.AddProgram("zjioec (61)");
			target.AddProgram("bjzlgik (154) -> iondfqm, izkhkai");
			target.AddProgram("eoxubh (92)");
			target.AddProgram("ftzhz (18)");
			target.AddProgram("fwjdwhg (62)");
			target.AddProgram("txkog (46)");
			target.AddProgram("rabdvok (57)");
			target.AddProgram("dfykpx (59)");
			target.AddProgram("lncdocs (70)");
			target.AddProgram("qyqid (69)");
			target.AddProgram("quybmbk (179) -> pmfuf, ubrevf");
			target.AddProgram("qkhudy (67)");
			target.AddProgram("grqtsex (80)");
			target.AddProgram("dijeym (61)");
			target.AddProgram("ancmoj (74)");
			target.AddProgram("lpvqp (17)");
			target.AddProgram("angyt (75)");
			target.AddProgram("tecducv (151) -> ftrzswp, sfztpf");
			target.AddProgram("podkl (78)");
			target.AddProgram("ieqgany (17)");
			target.AddProgram("nnnfykw (75)");
			target.AddProgram("bjtlzzh (133) -> syfccrr, rgzch");
			target.AddProgram("xoedja (1123) -> chrzza, cghtkzr, gzrfjk");
			target.AddProgram("pvdsg (74)");
			target.AddProgram("mqsth (258) -> bcwbp, idnvd, amhthnw, rfmgglc");
			target.AddProgram("wnaykx (68)");
			target.AddProgram("mdxcp (97)");
			target.AddProgram("jbsxc (68)");
			target.AddProgram("rcaajf (80)");
			target.AddProgram("reeuuic (66)");
			target.AddProgram("zhallzk (173) -> qkmqmg, tkgkl");
			target.AddProgram("kzroqbi (19)");
			target.AddProgram("lygtf (24) -> gqaefmb, xgowghi, nbxceyt, tboimc, rptgp, cdovdt");
			target.AddProgram("fmntbo (204)");
			target.AddProgram("mgwbaj (21)");
			target.AddProgram("zlxxdjc (54)");
			target.AddProgram("lalblzp (65)");
			target.AddProgram("rdfab (43)");
			target.AddProgram("gxprou (58) -> wyucu, grwcz, kbyijkc");
			target.AddProgram("qkseme (44) -> axnwb, zkqxpbq, crxji");
			target.AddProgram("vjcexcx (86)");
			target.AddProgram("nhmrdn (99)");
			target.AddProgram("gqaefmb (234) -> wdqjl, kbkqm");
			target.AddProgram("aenvjl (34) -> rknadpx, qreeg, wevbhta");
			target.AddProgram("koyzdbq (20)");
			target.AddProgram("idnvd (43)");
			target.AddProgram("qewavw (61) -> gkyph, byfbs, lhcinxf");
			target.AddProgram("htqjli (38)");
			target.AddProgram("jtqgtf (55)");
			target.AddProgram("evpav (31)");
			target.AddProgram("axnwb (97)");
			target.AddProgram("gzrfjk (781) -> sieovol, lmavxq, qqkctf");
			target.AddProgram("iauzkqz (81) -> axjcbuj, meqlt");
			target.AddProgram("vtdyp (180) -> twxtbol, cfihl, vucwhs");
			target.AddProgram("iomxv (226)");
			target.AddProgram("sihgu (99)");
			target.AddProgram("azysfe (45)");
			target.AddProgram("iwczlkt (69)");
			target.AddProgram("zeenwpx (22) -> nhmrdn, sihgu, uaknxb");
			target.AddProgram("jbaxm (293) -> qiveb, fczix, xrhjl, gavdkw, ptcccmw, puawqd");
			target.AddProgram("hirayas (57)");
			target.AddProgram("zwvtdhw (84) -> tujzoy, gtkkx");
			target.AddProgram("plbbbno (25)");
			target.AddProgram("sdlcqtb (76) -> gfepc, hxkatz");
			target.AddProgram("qbqjz (77)");
			target.AddProgram("tkqdly (21)");
			target.AddProgram("seyiftq (20)");
			target.AddProgram("lznju (96)");
			target.AddProgram("uamaay (43) -> ucjeppl, lfmzadj");
			target.AddProgram("tbkxpdv (71)");
			target.AddProgram("puoogd (95)");
			target.AddProgram("zkkok (1239) -> qtxfdex, fufzi, uamaay");
			target.AddProgram("bfkdbeh (162) -> blmsqb, vzeuayg, kbpnl, viubix");
			target.AddProgram("tthmac (1206) -> maubg, qewavw, jpeehl, pvzjsbf");
			target.AddProgram("hhldn (61) -> cujtqk, pvdsg, lmntml");
			target.AddProgram("zouklk (55)");
			target.AddProgram("nmvqwi (18)");
			target.AddProgram("cgnewz (179) -> gounu, icflka, yusue, zbjdebj, mevdoy, gvgnev, etfbf");
			target.AddProgram("sletcp (31)");
			target.AddProgram("adzvlgk (63)");
			target.AddProgram("fnoaz (96)");
			target.AddProgram("aaroa (121)");
			target.AddProgram("iksafw (41)");
			target.AddProgram("zfswj (26)");
			target.AddProgram("zwekns (66)");
			target.AddProgram("pkhvge (95)");
			target.AddProgram("fpkhun (185) -> jtqgtf, fwfad");
			target.AddProgram("bapvqa (93)");
			target.AddProgram("tyajj (135) -> jvhjtv, pxupwhx");
			target.AddProgram("lfmzadj (93)");
			target.AddProgram("alhkjxm (67) -> qqncuk, lywsab");
			target.AddProgram("lkhvhui (224) -> uufmp, qumacc");
			target.AddProgram("pqmyl (11)");
			target.AddProgram("qrdei (86)");
			target.AddProgram("fnvptes (297) -> cjnwipw, blwxqfp");
			target.AddProgram("ftuues (124) -> puoogd, gyhfl");
			target.AddProgram("azbjh (43)");
			target.AddProgram("epubm (92)");
			target.AddProgram("vusafsv (6) -> ivxnetm, syjew, csdrrx, ngonq, azfkwzp, awysiko, qlesgoz");
			target.AddProgram("jrigbij (80)");
			target.AddProgram("khbpnx (117) -> kpegrqm, mudup");
			target.AddProgram("qxyemg (7)");
			target.AddProgram("gkyph (58)");
			target.AddProgram("vbusaxq (68)");
			target.AddProgram("kxgxji (372)");
			target.AddProgram("lvihecc (33)");
			target.AddProgram("mjpcrh (13)");
			target.AddProgram("kpegrqm (87)");
			target.AddProgram("ohapkri (19)");
			target.AddProgram("phppbj (39)");
			target.AddProgram("hewzwp (34)");
			target.AddProgram("siujrb (42)");
			target.AddProgram("pnfwlas (232) -> mkuernu, edvqwvm");
			target.AddProgram("qrxso (46) -> azxoyif, kbehv, zuhkp");
			target.AddProgram("tpezujs (41)");
			target.AddProgram("zghut (5)");
			target.AddProgram("elpfsya (83)");
			target.AddProgram("vsvyj (242)");
			target.AddProgram("irkfc (14) -> rypyfha, cgagfib");
			target.AddProgram("nmyem (90)");
			target.AddProgram("njkxh (71)");
			target.AddProgram("ynxjgv (72)");
			target.AddProgram("ohvhpc (36)");
			target.AddProgram("tlfaxub (92)");
			target.AddProgram("iazmq (17)");
			target.AddProgram("yhdjwd (54)");
			target.AddProgram("vqumdju (45)");
			target.AddProgram("olylo (188)");
			target.AddProgram("dmkji (1094) -> hdkvbzv, cfyuogb, puxlsjo");
			target.AddProgram("dukup (72)");
			target.AddProgram("djpvps (31)");
			target.AddProgram("bokni (97)");
			target.AddProgram("jludr (7)");
			target.AddProgram("sdqzod (44)");
			target.AddProgram("uryqiso (183) -> rmbzvq, lvpdwy");
			target.AddProgram("eugwuhl (18) -> avpklqy, tytbgx, bdohoaa, smaygo, pvvbn, hgizeb, tchfafn");
			target.AddProgram("wgkxy (141) -> ryhlz, ohjax");
			target.AddProgram("ttiaks (9)");
			target.AddProgram("mpgge (50)");
			target.AddProgram("hdlfpj (46) -> bddii, konmy, mdwqmyg");
			target.AddProgram("mxoxo (117) -> icgwqn, vjstu");
			target.AddProgram("kbpxjg (225)");
			target.AddProgram("xthyeh (38)");
			target.AddProgram("dyxtot (51)");
			target.AddProgram("tcmexa (322) -> xhueuj, pqmyl");
			target.AddProgram("kbjazf (12) -> ljqmwwg, iksafw, tpezujs, tfjadw");
			target.AddProgram("sdnwo (75)");
			target.AddProgram("fwubo (53)");
			target.AddProgram("bfnkr (132) -> wlodpu, wavmnm, hcpim");
			target.AddProgram("eymlu (58)");
			target.AddProgram("fybpzfy (210) -> pqmsc, wufcpvr");
			target.AddProgram("tnngnq (27)");
			target.AddProgram("nsecr (24)");
			target.AddProgram("xhueuj (11)");
			target.AddProgram("hsnsncv (22)");
			target.AddProgram("oseqshg (76)");
			target.AddProgram("aflzz (1359) -> pkhvge, uyuyq");
			target.AddProgram("urqoabs (21)");
			target.AddProgram("aiwqhey (53)");
			target.AddProgram("hxqik (45)");
			target.AddProgram("zvsiqwe (63)");
			target.AddProgram("etfnmle (76)");
			target.AddProgram("eqreeik (27) -> vrezl, lvuah, ffrjb, ykuzfu");
			target.AddProgram("joxzy (253) -> fxnbfjk, czvdrpq, ubllrlw, hjsfv");
			target.AddProgram("zamoi (58)");
			target.AddProgram("okcck (61)");
			target.AddProgram("bwyjnu (60) -> pzuxx, mdfjh");
			target.AddProgram("ydfmxw (20)");
			target.AddProgram("upeezd (564) -> ozjzmh, fzbbm, fjhht, wrzwgxf, nvkqru, jorbfl");
			target.AddProgram("hxlsxdj (19)");
			target.AddProgram("hsvveid (10)");
			target.AddProgram("xbiuhd (89)");
			target.AddProgram("cfyuogb (13) -> hlyodf, tvtgaan, qsewkq");
			target.AddProgram("kndobxz (75)");
			target.AddProgram("wlfngqq (484) -> pgvds, rvzkv, azycte, igoifwl, zfgqhf, wlcjt");
			target.AddProgram("ctoruu (72) -> ynxjgv, cexrf");
			target.AddProgram("ashxpav (59) -> quybmbk, sydqf, qnblxrh, ysfevlj, xgpmq, stgickl");
			target.AddProgram("njibgv (688) -> ahmknyy, vruiy, wlfngqq, juvhkoc, ehefb, qfuoayy");
			target.AddProgram("elcvqr (19)");
			target.AddProgram("hmvin (176)");
			target.AddProgram("lkstwl (45)");
			target.AddProgram("neafgd (76)");
			target.AddProgram("dbbsyeo (79) -> jldgbkx, nkfpci");
			target.AddProgram("ohitm (1133) -> aaeeqh, dlodc, rxerq");
			target.AddProgram("ivbrype (72)");
			target.AddProgram("jgmyc (1366) -> oaefi, mzdxg, muzkuai, hblnwza");
			target.AddProgram("kixlvf (1906) -> eledia, ioexd, mamllly");
			target.AddProgram("ngonq (243) -> oydwkrv, rnibhd");
			target.AddProgram("ubqbhos (87)");
			target.AddProgram("eevyny (77)");
			target.AddProgram("vwrhg (72)");
			target.AddProgram("fwfad (55)");
			target.AddProgram("smaygo (4616) -> hmgrlpj, fbnbt, nfdvsc");
			target.AddProgram("arbrp (48) -> vlysbd, njkxh");
			target.AddProgram("ggzzt (41) -> fkilb, iartkgt");
			target.AddProgram("cxflah (122) -> oxyltk, clrfkgl");
			target.AddProgram("pkpgu (95) -> nnzhve, wcvxg");
			target.AddProgram("httgiox (77)");
			target.AddProgram("lnttud (63)");
			target.AddProgram("nvpgfzh (68)");
			target.AddProgram("ootknbf (45)");
			target.AddProgram("eledia (6) -> maqzwn, iplfnd");
			target.AddProgram("srpcy (91)");
			target.AddProgram("jpeehl (157) -> paqbnl, jqwhun");
			target.AddProgram("clwbp (45)");
			target.AddProgram("xubhat (70)");
			target.AddProgram("umwer (17)");
			target.AddProgram("rnibhd (69)");
			target.AddProgram("zfgqhf (160) -> dbrxe, fyubj");
			target.AddProgram("zfngau (94)");
			target.AddProgram("ctytwcc (18)");
			target.AddProgram("igbqenq (212) -> fuyldc, dxlttzs");
			target.AddProgram("quhkp (88)");
			target.AddProgram("wrzwgxf (77) -> kgdtem, kndobxz");
			target.AddProgram("twngkp (59)");
			target.AddProgram("gperhh (1195) -> sspng, pjtsef, blbzqf");
			target.AddProgram("nyjgkav (191) -> jwvcm, kxjnq");
			target.AddProgram("tijgc (94)");
			target.AddProgram("bsoesu (47) -> mhdauqb, bfaak");
			target.AddProgram("xzcfko (21) -> bdslm, bywohrp, tkhgo");
			target.AddProgram("wwpxh (51) -> luufi, aiwqhey");
			target.AddProgram("gwlrdbk (97)");
			target.AddProgram("bbueq (52)");
			target.AddProgram("kidbaiy (38)");
			target.AddProgram("gqcmcc (59)");
			target.AddProgram("uasrsi (95) -> cujdv, bvdnvep, vzldrq, vdgvmd");
			target.AddProgram("lxjbzu (12) -> nsqfu, nxkpbs, ebeitz, lygtf");
			target.AddProgram("syhjziw (24)");
			target.AddProgram("jqjmgyv (85)");
			target.AddProgram("dvhcixe (17)");
			target.AddProgram("sqcwjaa (22)");
			target.AddProgram("robfhmz (77)");
			target.AddProgram("qfbagb (42)");
			target.AddProgram("pubgkhb (75)");
			target.AddProgram("wdqjl (88)");
			target.AddProgram("qanpeab (9) -> qylxl, kymwev, fpkhun, jljwoo, kbpklq, rppgdnf, qjjuk");
			target.AddProgram("vsyolk (299)");
			target.AddProgram("vgysvve (75)");
			target.AddProgram("wbflq (145) -> wdwfjh, suhso");
			target.AddProgram("izchcj (83)");
			target.AddProgram("kfvur (40)");
			target.AddProgram("fvagct (176)");
			target.AddProgram("tksiwle (78) -> xjwvvik, pwmqpk");
			target.AddProgram("iquxck (6442) -> zubbg, tpjuj, zkkok, upeezd, nafjtip");
			target.AddProgram("hojpgpo (58) -> shyxe, xkzzcqt, ymqqpug, eqmkgj");
			target.AddProgram("qzvrq (1178) -> gxprou, rpiefl, xzndm, tchaqbm");
			target.AddProgram("ogjeuhl (2016) -> argdqd, euezshv");
			target.AddProgram("ieeecih (98)");
			target.AddProgram("rhyglf (54)");
			target.AddProgram("txyqy (178) -> bbiczh, lfoiu");
			target.AddProgram("fjkjmhd (192) -> ntjmdri, vzlvim");
			target.AddProgram("qzqtysl (37)");
			target.AddProgram("yqdsxvc (63)");
			target.AddProgram("wufcpvr (72)");
			target.AddProgram("ewalq (70)");
			target.AddProgram("xeeuxiz (33) -> rkevnnd, mkqtej");
			target.AddProgram("ubhsnqw (20)");
			target.AddProgram("vkikri (82)");
			target.AddProgram("pooon (22) -> bkrctx, tybjmqm, wxtrq, hgynpc, epblwo, hnswwt, kxgxji");
			target.AddProgram("xsepbvk (77)");
			target.AddProgram("xexswl (97)");
			target.AddProgram("igrahel (146) -> uzbqa, ckakkja, ihqfqm");
			target.AddProgram("lvqkp (66) -> jvsmwee, quhkp, cufau");
			target.AddProgram("zubbg (1077) -> hhldn, kvyrc, fhsdpg");
			target.AddProgram("gvgnev (289)");
			target.AddProgram("icjmhii (20)");
			target.AddProgram("dbsbuqp (97) -> ahnkcy, ebootd");
			target.AddProgram("ygsjv (137) -> fzqita, llale");
			target.AddProgram("tjnuf (180) -> mwkct, qclnd");
			target.AddProgram("pdowqq (17)");
			target.AddProgram("zkeep (32)");
			target.AddProgram("dknly (78)");
			target.AddProgram("bmzlp (83)");
			target.AddProgram("cghtkzr (418) -> holuib, ovkpba, ifvkdba");
			target.AddProgram("cymvz (66)");
			target.AddProgram("tqzmvz (80)");
			target.AddProgram("npmkxsb (84)");
			target.AddProgram("hyolftw (39) -> vkgqysh, kqjfnb, hxeia");
			target.AddProgram("fjrwy (5)");
			target.AddProgram("dfywfie (63) -> nfvliuy, risguql");
			target.AddProgram("aspoy (63)");
			target.AddProgram("ydnsnh (29)");
			target.AddProgram("jyoevqm (76)");
			target.AddProgram("jacplh (133) -> ahrynjm, aenrksb");
			target.AddProgram("yiozhnf (93)");
			target.AddProgram("yqhss (76)");
			target.AddProgram("kmujst (284) -> iwsppaw, axjqq, mljlpfo");
			target.AddProgram("trnpdnb (78)");
			target.AddProgram("hhrdosf (13)");
			target.AddProgram("zrvff (210) -> odhwzy, sfpveq");
			target.AddProgram("odirpnl (20)");
			target.AddProgram("rknadpx (63)");
			target.AddProgram("brnqhc (70) -> neclo, ppstt, ktyyedq, xnfstk");
			target.AddProgram("sctzxf (88)");
			target.AddProgram("bddii (60)");
			target.AddProgram("vrndjn (19)");
			target.AddProgram("swwtm (18)");
			target.AddProgram("cqxav (72)");
			target.AddProgram("rzaocr (98)");
			target.AddProgram("juavhi (20) -> krhkthl, bbueq, gdmuqn");
			target.AddProgram("vugudp (71)");
			target.AddProgram("zoifh (63)");
			target.AddProgram("qwwmx (71)");
			target.AddProgram("fdvgk (63)");
			target.AddProgram("xzcix (91)");
			target.AddProgram("cufau (88)");
			target.AddProgram("qbdisnk (21)");
			target.AddProgram("ozjzmh (81) -> lvlfju, uraugcn");
			target.AddProgram("mwbpro (51)");
			target.AddProgram("zrioi (156) -> hsvveid, xqssuna");
			target.AddProgram("xqmhigw (34)");
			target.AddProgram("fufjkl (57)");
			target.AddProgram("kvyrc (133) -> sdnwo, acrly");
			target.AddProgram("bhtoyru (186) -> icxhhje, ighndd, fbdrf");
			target.AddProgram("gfluo (55)");
			target.AddProgram("ighndd (80)");
			target.AddProgram("blmsqb (10)");
			target.AddProgram("gjjgkga (69)");
			target.AddProgram("bsmryo (22)");
			target.AddProgram("owkjav (56)");
			target.AddProgram("kymwev (215) -> nkywqaj, hazyoke");
			target.AddProgram("tzpxj (134) -> ujhkl, gwvhjfe");
			target.AddProgram("ymqqpug (93)");
			target.AddProgram("rfmgglc (43)");
			target.AddProgram("evhgkft (19)");
			target.AddProgram("nikvfs (34)");
			target.AddProgram("argdqd (65)");
			target.AddProgram("sxzwplf (19)");
			target.AddProgram("pydtt (45)");
			target.AddProgram("ctxwkkt (25)");
			target.AddProgram("axjcbuj (35)");
			target.AddProgram("pustj (742) -> juavhi, bwyjnu, fvagct, kbjazf, oyomma");
			target.AddProgram("dapds (32)");
			target.AddProgram("hphzmhs (17)");
			target.AddProgram("wavmnm (65)");
			target.AddProgram("fcdww (40)");
			target.AddProgram("eunfszw (28)");
			target.AddProgram("qifofxk (83)");
			target.AddProgram("npzlka (99) -> lijmpm, dwnys, ijajh, gfluo");
			target.AddProgram("nhtxs (252) -> dvhcixe, uwopuvj");
			target.AddProgram("qvjwgkp (160) -> tjwodb, juvwqt");
			target.AddProgram("fzbbm (137) -> gheqw, nrsrwb");
			target.AddProgram("lduim (53)");
			target.AddProgram("zowqczm (96)");
			target.AddProgram("fqyogt (45)");
			target.AddProgram("yxavos (89)");
			target.AddProgram("gyhfl (95)");
			target.AddProgram("bjwgltq (61)");
			target.AddProgram("vljijeh (150) -> xfwgll, evmkzjr");
			target.AddProgram("cawvue (81) -> cslrgbh, vkpnxs");
			target.AddProgram("ijlmcnx (78)");
			target.AddProgram("mjmskc (399) -> slolo, jludr");
			target.AddProgram("htpboal (69)");
			target.AddProgram("mjseecw (68)");
			target.AddProgram("wjmbivd (63) -> rodegh, dwhxnif, mqafr");
			target.AddProgram("eqtmes (47)");
			target.AddProgram("muzkuai (77) -> dhmhbw, gqwfut");
			target.AddProgram("kohici (96)");
			target.AddProgram("cwgux (18)");
			target.AddProgram("iwsppaw (150) -> axfvokp, qagul");
			target.AddProgram("pqmsc (72)");
			target.AddProgram("qnuusbq (15)");
			target.AddProgram("nofdxpt (491) -> iauzkqz, cayxz, ygsjv");
			target.AddProgram("wgsgyv (76)");
			target.AddProgram("tchfafn (31649) -> qrxso, xoedja, fapkonf");
			target.AddProgram("pwlpeu (98)");
			target.AddProgram("gpqcq (31)");
			target.AddProgram("cnxyhg (50)");
			target.AddProgram("ryhlz (56)");
			target.AddProgram("kmvcjir (89)");
			target.AddProgram("slolo (7)");
			target.AddProgram("fqdccsa (91)");
			target.AddProgram("xtbdj (78)");
			target.AddProgram("nniqh (59)");
			target.AddProgram("jwvcm (92)");
			target.AddProgram("myerj (204)");
			target.AddProgram("oepwc (21)");
			target.AddProgram("awclg (49)");
			target.AddProgram("igoifwl (176) -> dijeym, okcck");
			target.AddProgram("qcsjl (33)");
			target.AddProgram("asihmc (32)");
			target.AddProgram("fpekhb (344) -> lqjnx, xhqxyc, swxncwt, vljijeh");
			target.AddProgram("xytulz (79)");
			target.AddProgram("vlysbd (71)");
			target.AddProgram("busosd (55)");
			target.AddProgram("kbkqm (88)");
			target.AddProgram("gpvlztd (106) -> tqzmvz, aqdjk");
			target.AddProgram("cgagfib (95)");
			target.AddProgram("jbdtgk (29)");
			target.AddProgram("rpjlb (68)");
			target.AddProgram("xazpni (92)");
			target.AddProgram("meybf (54)");
			target.AddProgram("wlczi (246) -> yxotxz, xronh");
			target.AddProgram("birvaha (275) -> koyzdbq, odirpnl, jggzx");
			target.AddProgram("oavnz (22)");
			target.AddProgram("blwaz (247) -> nebitb, vrndjn");
			target.AddProgram("yalugkr (75)");
			target.AddProgram("yusue (91) -> owsoywa, pobecj");
			target.AddProgram("hfzyzt (124) -> mhvhtg, djkaku");
			target.AddProgram("jvjezrv (31)");
			target.AddProgram("uyuyq (95)");
			target.AddProgram("scghvn (98)");
			target.AddProgram("pndayy (1340) -> ftzhz, yedwosl");
			target.AddProgram("smvodeb (124)");
			target.AddProgram("hgynpc (267) -> bvfee, prxlb, iwkqae");
			target.AddProgram("owjjja (1495) -> lfpwycg, vqntk, xzjbmpu");
			target.AddProgram("wvhdyg (29) -> dlbsqa, fnoaz, zowqczm");
			target.AddProgram("jotnlgm (79) -> povsm, nrvqpd, iufypzm");
			target.AddProgram("fzyftv (93)");
			target.AddProgram("bdslm (59)");
			target.AddProgram("stguc (133) -> evqfv, lkuelr");
			target.AddProgram("fagyf (589) -> jjxcsxg, khbpnx, wklmecc, ajxmlfp, iegjd, eqreeik, beyphy");
			target.AddProgram("stgickl (229) -> kozlia, znuin");
			target.AddProgram("lviohn (71)");
			target.AddProgram("actlu (15)");
			target.AddProgram("gxcwynf (80) -> kyfcsou, jelcp");
			target.AddProgram("azvltq (72)");
			target.AddProgram("kgdtem (75)");
			target.AddProgram("juaquyw (164) -> uembuig, jajbpsk");
			target.AddProgram("eyfvei (103) -> zgxczmq, lnreval");
			target.AddProgram("hcpim (65)");
			target.AddProgram("rludm (351) -> sletcp, djpvps");
			target.AddProgram("gjmbm (25)");
			target.AddProgram("ffrjb (66)");
			target.AddProgram("kyokkl (89)");
			target.AddProgram("zjchuge (20)");
			target.AddProgram("uxqlce (57)");
			target.AddProgram("gtnqtd (59)");
			target.AddProgram("uufmp (60)");
			target.AddProgram("jqgjdku (68)");
			target.AddProgram("rlyui (73)");
			target.AddProgram("fyubj (69)");
			target.AddProgram("twxtbol (49)");
			target.AddProgram("xdehk (63)");
			target.AddProgram("pobecj (99)");
			target.AddProgram("iplfnd (37)");
			target.AddProgram("guyju (86)");
			target.AddProgram("jbaztvm (53) -> jqvjr, eyfvei, fkfyeej, paqngfj, basiy, pkivl, vsyolk");
			target.AddProgram("mamllly (66) -> qxyemg, umkwllw");
			target.AddProgram("pxupwhx (91)");
			target.AddProgram("nxkpbs (1707) -> cnvir, yfwki, bhfeafe");
			target.AddProgram("xezse (11)");
			target.AddProgram("qreeg (63)");
			target.AddProgram("puawqd (256) -> cwwpev, eihkuqx");
			target.AddProgram("yrtlizo (291) -> letwfzz, oavnz");
			target.AddProgram("hyywt (18)");
			target.AddProgram("dfqvxnn (73)");
			target.AddProgram("letwfzz (22)");
			target.AddProgram("alcioc (314)");
			target.AddProgram("msekejl (77) -> utvdgr, hkfgksw");
			target.AddProgram("ybfyes (50)");
			target.AddProgram("bzvqqp (86) -> vjmzqbb, gzakvk");
			target.AddProgram("iavld (19)");
			target.AddProgram("syjew (204) -> tgtrjko, xgdolgm, jngbnk");
			target.AddProgram("pwzvu (66)");
			target.AddProgram("dnlao (51)");
			target.AddProgram("oidmfs (97)");
			target.AddProgram("ckyoc (40)");
			target.AddProgram("etfbf (239) -> oitpd, nhxyn");
			target.AddProgram("lvpdwy (19)");
			target.AddProgram("xzuedm (212) -> dyxtot, dnlao");
			target.AddProgram("hdsth (32) -> qrdei, guyju");
			target.AddProgram("ygidtwv (66)");
			target.AddProgram("rypyfha (95)");
			target.AddProgram("gdmuqn (52)");
			target.AddProgram("nbxceyt (320) -> taizyha, pydtt");
			target.AddProgram("pzuxx (58)");
			target.AddProgram("vpvcum (91) -> nvlpgon, sctzxf");
			target.AddProgram("lkokq (77)");
			target.AddProgram("nrevor (596) -> xeeuxiz, jqeabja, fjklelc, dkgsxvj");
			target.AddProgram("konmy (60)");
			target.AddProgram("nigdlq (846) -> hdsth, hlxlrjq, txyqy, myerj, fmntbo, irkfc");
			target.AddProgram("djsexcr (22)");
			target.AddProgram("aodkqlr (185) -> ymxpav, kbmrrew");
			target.AddProgram("wubxbc (43) -> htqjli, lpjbjju, hbncy");
			target.AddProgram("xlyzym (57)");
			target.AddProgram("xgpmq (126) -> dkjsfxs, dfykpx, gtnqtd");
			target.AddProgram("kmjqzw (63) -> avjfqex, tqqldx, ancmoj");
			target.AddProgram("nmteeca (80)");
			target.AddProgram("twogxyg (11)");
			target.AddProgram("cwkdjn (29)");
			target.AddProgram("tasqwda (95)");
			target.AddProgram("cayxz (33) -> nplbgrk, twngkp");
			target.AddProgram("ovzcdi (42)");
			target.AddProgram("fmfkcp (71)");
			target.AddProgram("ompeys (207) -> dhpviei, plbbbno");
			target.AddProgram("ucjeppl (93)");
			target.AddProgram("mrshnke (18)");
			target.AddProgram("ytbwqwb (51)");
			target.AddProgram("lrxzg (66)");
			target.AddProgram("luasrvp (1476) -> mnvlfcf, ofxag, xzcfko");
			target.AddProgram("fhbjovx (1553) -> tmmwda, yibbu, tzpxj");
			target.AddProgram("wrquv (50) -> zlxxdjc, mdkfx, woqvn");
			target.AddProgram("odhwzy (38)");
			target.AddProgram("onmod (99) -> flwhrzk, jvjezrv, umopgq, xjpuoil");
			target.AddProgram("bhwxgp (74)");
			target.AddProgram("hmlvv (75) -> bsoesu, qucnu, kbpxjg");
			target.AddProgram("eghfd (13)");
			target.AddProgram("zknngyu (12) -> izchcj, bcxnm, mzlub, itcgsx");
			target.AddProgram("vruiy (711) -> aenvjl, onmod, ggzzt, daiyp, lrxyqgr, uvdpata, jbwoozn");
			target.AddProgram("xmett (76)");
			target.AddProgram("wrnmwy (20)");
			target.AddProgram("civhlqc (79)");
			target.AddProgram("tchaqbm (121) -> snluaf, uvjevu, kpxrk");
			target.AddProgram("skouwt (671) -> qvjwgkp, uzqnl, gghqilu, kpmyxk, ckgotfs, edbemy, nhtxs");
			target.AddProgram("uxddlkq (32)");
			target.AddProgram("lcourm (43)");
			target.AddProgram("ibuilzl (75)");
			target.AddProgram("pwajo (93)");
			target.AddProgram("nafjtip (1182) -> cxflah, insxh, iyosp, zyqkcmb");
			target.AddProgram("fserz (90)");
			target.AddProgram("yshith (56)");
			target.AddProgram("vvukaca (50)");
			target.AddProgram("pcwawh (46)");
			target.AddProgram("mevdoy (289)");
			target.AddProgram("hmgrlpj (66) -> pnqrgfk, luasrvp, ahrfh, tbfce, drjmjug, nigdlq, omytneg");
			target.AddProgram("xkzzcqt (93)");
			target.AddProgram("xronh (42)");
			target.AddProgram("lywsab (77)");
			target.AddProgram("icflka (157) -> pwzvu, wqtku");
			target.AddProgram("iqegs (345) -> yrmqu, swtks, twzglew, fmcjr");
			target.AddProgram("zlaxh (47)");
			target.AddProgram("itooipv (68)");
			target.AddProgram("ieiha (97)");
			target.AddProgram("sxrzzuy (13) -> hcorylb, itluk, ybjbz, igblzk");
			target.AddProgram("tgtrjko (59)");
			target.AddProgram("qclnd (11)");
			target.AddProgram("qfqkz (15) -> xmett, etfnmle");
			target.AddProgram("weaier (96)");
			target.AddProgram("yznahfs (102) -> wubxbc, vtewtb, jacplh, wwpxh, zhdwu, digpoav");
			target.AddProgram("xrhjl (216) -> dhrun, ltseugc");
			target.AddProgram("jngbnk (59)");
			target.AddProgram("tujzoy (91)");
			target.AddProgram("aijmghs (28)");
			target.AddProgram("ieabomm (15)");
			target.AddProgram("siulcz (93)");
			target.AddProgram("yqeuhw (42)");
			target.AddProgram("hxkatz (50)");
			target.AddProgram("gpzqcqk (27)");
			target.AddProgram("nnzhve (81)");
			target.AddProgram("evwtu (72)");
			target.AddProgram("gqwfut (50)");
			target.AddProgram("huhxf (299) -> uspjc, npmkxsb");
			target.AddProgram("ukkmfh (76)");
			target.AddProgram("rptgp (296) -> xthyeh, kidbaiy, rjumsra");
			target.AddProgram("wlodpu (65)");
			target.AddProgram("utvdgr (22)");
			target.AddProgram("qjjuk (109) -> iarbj, vlbkhb");
			target.AddProgram("mnvfi (47)");
			target.AddProgram("gfepc (50)");
			target.AddProgram("mkomwy (86) -> ktfbjoo, zrvff, hgzsxur");
			target.AddProgram("fzvllyz (26)");
			target.AddProgram("whrdhq (2578) -> uymwt, dgjqciq");
			target.AddProgram("nwfykuw (2136) -> jonbur, izuxb");
			target.AddProgram("ooiwbe (49)");
			target.AddProgram("nhxyn (25)");
			target.AddProgram("hyxxm (743) -> hojpgpo, hragl, mqsth");
			target.AddProgram("sxxnze (25)");
			target.AddProgram("swxncwt (34) -> zwekns, reeuuic");
			target.AddProgram("ruuerqk (43)");
			target.AddProgram("zhdwu (17) -> ewalq, gabbp");
			target.AddProgram("hidmpw (26)");
			target.AddProgram("kpmyxk (247) -> icqkc, mjpcrh, uvcsl");
			target.AddProgram("jjsbd (15)");
			target.AddProgram("csvni (19)");
			target.AddProgram("gavdkw (38) -> ztpysan, zvsiqwe, zoifh, xdehk");
			target.AddProgram("darwcoj (2168) -> yffnz, igrahel, dmkji, juqrwwm, pndayy, nrevor");
			target.AddProgram("selfpoj (46) -> xsepbvk, liida, dyaayff, ywhmyp");
			target.AddProgram("lvlfju (73)");
			target.AddProgram("azycte (298)");
			target.AddProgram("gheqw (45)");
			target.AddProgram("tnntrax (34)");
			target.AddProgram("nfdvsc (4824) -> kenpyrt, ytqrut, pustj, hbymky, tpvvbr, lcfsu");
			target.AddProgram("qsewkq (27)");
			target.AddProgram("pxncq (98)");
			target.AddProgram("dyaayff (77)");
			target.AddProgram("umopgq (31)");
			target.AddProgram("yuepo (51)");
			target.AddProgram("plysamb (11) -> yuwoa, vwrhg");
			target.AddProgram("hbzkf (51)");
			target.AddProgram("qiniyf (84)");
			target.AddProgram("oitpd (25)");
			target.AddProgram("kqdus (52) -> bwhjal, vbusaxq");
			target.AddProgram("tytbgx (6588) -> ynseh, uqqclia, darwcoj, eooiuq");
			target.AddProgram("unuvi (52) -> pvxof, qcdsvv");
			target.AddProgram("eihkuqx (17)");
			target.AddProgram("sbogacc (264) -> qcsjl, wttimqr");
			target.AddProgram("ajxmlfp (225) -> lvihecc, yanat");
			target.AddProgram("rqryd (132) -> pmebb, qfbagb");
			target.AddProgram("raucx (44)");
			target.AddProgram("xckzcq (66)");
			target.AddProgram("uiyxk (204) -> vgysvve, qnpzxal");
			target.AddProgram("kirvox (159) -> jerwsi, nmteeca");
			target.AddProgram("wepwf (32)");
			target.AddProgram("zvqupa (98)");
			target.AddProgram("uzbqa (376) -> umwer, iazmq");
			target.AddProgram("lcsqza (68)");
			target.AddProgram("qhlslym (147) -> gaxkntb, eymlu");
			target.AddProgram("fqskwj (51)");
			target.AddProgram("hragl (244) -> kfpxhb, mcxti, fwjdwhg");
			target.AddProgram("hjsfv (8)");
			target.AddProgram("ncrotbi (68)");
			target.AddProgram("ymxpav (38)");
			target.AddProgram("ntqdxv (16)");
			target.AddProgram("ynbruov (14)");
			target.AddProgram("sieovol (231)");
			target.AddProgram("pqknhsq (1031) -> gldorrf, jcqgj, fxptqn");
			target.AddProgram("yviutlw (31) -> gjmkox, hirayas, xlyzym");
			target.AddProgram("paqngfj (161) -> qyqid, htpboal");
			target.AddProgram("wohpoh (75)");
			target.AddProgram("hatfl (6172) -> sqygj, nofdxpt, mkomwy, kmujst");
			target.AddProgram("cgwnor (89)");
			target.AddProgram("jelcp (68)");
			target.AddProgram("azfkwzp (339) -> eflcxi, mgwbaj");
			target.AddProgram("nadwsc (113) -> ohvhpc, zvqyr, crlkolg");
			target.AddProgram("fjhht (193) -> ieqgany, hphzmhs");
			target.AddProgram("edmfm (80)");
			target.AddProgram("cjnwipw (10)");
			target.AddProgram("hvgum (2381) -> dfqvxnn, kuhybd, rdbbda, rlyui");
			target.AddProgram("gyveijp (34)");
			target.AddProgram("bcxnm (83)");
			target.AddProgram("vzldrq (18)");
			target.AddProgram("cfihl (49)");
			target.AddProgram("nxqswd (96)");
			target.AddProgram("xhnwej (85)");
			target.AddProgram("uvcsl (13)");
			target.AddProgram("kenpyrt (282) -> zgvpy, tntib, drvxvk, htojdr, gqlnaho");
			target.AddProgram("fzqita (7)");
			target.AddProgram("vznfkp (97) -> zfngau, tijgc");
			target.AddProgram("rlfbix (79) -> bokni, rjhws, ieiha, rjkumo");
			target.AddProgram("ckswfrb (48)");
			target.AddProgram("hbncy (38)");
			target.AddProgram("paioxf (25)");
			target.AddProgram("zuhkp (1365) -> bjdlb, ihimta, ffejzo");
			target.AddProgram("aqubpi (11)");
			target.AddProgram("vkpnxs (64)");
			target.AddProgram("itcgsx (83)");
			target.AddProgram("xjbmdc (142) -> tmbkt, ywhxoi");
			target.AddProgram("vucwhs (49)");
			target.AddProgram("vuldc (70)");
			target.AddProgram("lcmek (741) -> tksiwle, bfkdbeh, tjnuf, yviutlw");
			target.AddProgram("ysfevlj (205) -> awclg, ooiwbe");
			target.AddProgram("grwcz (66)");
			target.AddProgram("yuwoa (72)");
			target.AddProgram("cprsra (32)");
			target.AddProgram("tvtgaan (27)");
			target.AddProgram("pjtsef (59) -> podkl, rnkvgzf, bqwgm");
			target.AddProgram("cwehc (29)");
			target.AddProgram("wcvxg (81)");
			target.AddProgram("ahmknyy (637) -> qkqyelb, vtdyp, wjmbivd, bfnkr, oujtz");
			target.AddProgram("yieehh (259) -> lviohn, qwwmx");
			target.AddProgram("hgizeb (5324) -> tfzsqj, njibgv, izjppbx");
			target.AddProgram("jvhjtv (91)");
			target.AddProgram("ksuhtas (14) -> qvykht, wahfxls");
			target.AddProgram("fkilb (91)");
			target.AddProgram("emigqf (46)");
			target.AddProgram("xgowghi (256) -> lkokq, eevyny");
			target.AddProgram("vqntk (21) -> hobnerj, yxavos, kyokkl, mzrze");
			target.AddProgram("vrbjw (57)");
			target.AddProgram("wttimqr (33)");
			target.AddProgram("pvzjsbf (143) -> wvaketk, qklhqlf");
			target.AddProgram("solooh (188) -> ffcwobn, fmfkcp");
			target.AddProgram("qmygary (95)");
			target.AddProgram("ztruf (44) -> gfhuv, fcdww");
			target.AddProgram("qtxfdex (191) -> iavld, elcvqr");
			target.AddProgram("mzrze (89)");
			target.AddProgram("hhpysjd (34)");
			target.AddProgram("bqwgm (78)");
			target.AddProgram("qfuoayy (74) -> xzuedm, ftuues, alcioc, lhauud, ozvtq, szcqd, brnqhc");
			target.AddProgram("yvdilfo (32)");
			target.AddProgram("grbpi (80)");
			target.AddProgram("khjqt (87)");
			target.AddProgram("avpklqy (68) -> werlnym, tkoxc, iquxck");
			target.AddProgram("jjxcsxg (18) -> eatoyd, lqsgphu, fqdccsa");
			target.AddProgram("kdsscve (310) -> sqcwjaa, djsexcr");
			target.AddProgram("veegvvc (53)");
			target.AddProgram("umjdo (69)");
			target.AddProgram("bkrbfap (96)");
			target.AddProgram("baljt (18)");
			target.AddProgram("qorpdxg (72)");
			target.AddProgram("wahfxls (88)");
			target.AddProgram("unfpyg (24)");
			target.AddProgram("zdelwv (57)");
			target.AddProgram("fhsdpg (143) -> lncdocs, xubhat");
			target.AddProgram("ahrynjm (12)");
			target.AddProgram("pvxof (82)");
			target.AddProgram("ynseh (5204) -> hpaeg, yznahfs, cxapyp, rtwwdrh, kuusoe");
			target.AddProgram("bmcsya (85)");
			target.AddProgram("thzvetu (65)");
			target.AddProgram("uyfzha (50)");
			target.AddProgram("ghzvdod (7)");
			target.AddProgram("rjumsra (38)");
			target.AddProgram("qvykht (88)");
			target.AddProgram("awysiko (93) -> qorpdxg, ccdpnr, evwtu, cjnab");
			target.AddProgram("daiyp (133) -> clwbp, azysfe");
			target.AddProgram("bywohrp (59)");
			target.AddProgram("pppsd (29)");
			target.AddProgram("qagul (35)");
			target.AddProgram("axjqq (106) -> xrppd, fufjkl");
			target.AddProgram("uvdpata (131) -> emigqf, tubcr");
			target.AddProgram("vrezl (66)");
			target.AddProgram("fausgp (32)");
			target.AddProgram("wjyekj (56)");
			target.AddProgram("ckdwk (104) -> wlxwq, vuldc");
			target.AddProgram("dyacjh (24)");
			target.AddProgram("yanat (33)");
			target.AddProgram("tboimc (18) -> sigya, ieeecih, scghvn, zvqupa");
			target.AddProgram("pmfuf (62)");
			target.AddProgram("oxyltk (32)");
			target.AddProgram("gzakvk (89)");
			target.AddProgram("shfyok (14)");
			target.AddProgram("znuin (37)");
			target.AddProgram("tpvvbr (974) -> rqryd, ctoruu, unuvi");
			target.AddProgram("vzeuayg (10)");
			target.AddProgram("hmytpw (178) -> ywacbmq, ubqbhos");
			target.AddProgram("vxfpzku (797) -> zibll, kqdus, fzqdsv, olylo");
			target.AddProgram("ovhos (46)");
			target.AddProgram("amhthnw (43)");
			target.AddProgram("cndqzdm (50)");
			target.AddProgram("adyni (11474) -> kmjqzw, mxoxo, joxzy, lxuiwb, vznfkp, blwaz");
			target.AddProgram("eqmkgj (93)");
			target.AddProgram("lijmpm (55)");
			target.AddProgram("sqygj (848) -> jiwpf, ckswfrb");
			target.AddProgram("gcpipz (49)");
			target.AddProgram("czvdrpq (8)");
			target.AddProgram("suupi (76)");
			target.AddProgram("zljgpq (27)");
			target.AddProgram("werlnym (34) -> gdneruv, byhatd, wusxwq, vusafsv, skouwt, hvgum");
			target.AddProgram("hnswwt (32) -> mbcpufw, xhnwej, ovuesou, jqjmgyv");
			target.AddProgram("txzlem (467)");
			target.AddProgram("mdwqmyg (60)");
			target.AddProgram("vdtdpz (84)");
			target.AddProgram("ntjmdri (10)");
			target.AddProgram("zlbfpnu (71)");
			target.AddProgram("digpoav (61) -> dapds, jwutq, uxddlkq");
			target.AddProgram("kfpxhb (62)");
			target.AddProgram("nldvtr (84)");
			target.AddProgram("ybjbz (97)");
			target.AddProgram("ptcccmw (116) -> khjqt, pzfdzb");
			target.AddProgram("rdomi (46)");
			target.AddProgram("goiwg (162) -> lxngrgu, ovtoke, mpmmos");
			target.AddProgram("ialmhy (206) -> iiktsrr, acgef, tkdsfz");
			target.AddProgram("dkohgp (119) -> bvoqpkb, cwgux");
			target.AddProgram("nhbff (51)");
			target.AddProgram("nrywfm (83)");
			target.AddProgram("qtatze (299) -> mrshnke, hekihe");
			target.AddProgram("rnzpmw (92)");
			target.AddProgram("mgqziu (20)");
			target.AddProgram("dlbsqa (96)");
			target.AddProgram("jrquxee (72)");
			target.AddProgram("meqlt (35)");
			target.AddProgram("hbymky (774) -> qqqvdsu, mztwrvf, wrquv, oppmeig");
			target.AddProgram("sjmci (54)");
			target.AddProgram("oyomma (125) -> ynzpsk, jygrpp, cebdo");
			target.AddProgram("ubrevf (62)");
			target.AddProgram("ezgvb (20)");
			target.AddProgram("lqjnx (166)");
			target.AddProgram("llale (7)");
			target.AddProgram("tybjmqm (372)");
			target.AddProgram("byfbs (58)");
			target.AddProgram("fmcjr (14)");
			target.AddProgram("gaxkntb (58)");
			target.AddProgram("jonbur (33)");
			target.AddProgram("asbiye (18)");
			target.AddProgram("vcrsnrf (11)");
			target.AddProgram("zapjqj (54)");
			target.AddProgram("deqcnp (142) -> ivrnod, ovzcdi");
			target.AddProgram("jpwtw (81)");
			target.AddProgram("renqhyi (52)");
			target.AddProgram("tfregkr (53) -> tnntrax, jfuzgpw");
			target.AddProgram("clrfkgl (32)");
			target.AddProgram("cidfent (104) -> zapjqj, gaspe");
			target.AddProgram("vxbio (75)");
			target.AddProgram("ykuzfu (66)");
			target.AddProgram("itzdby (331) -> itooipv, nvpgfzh");
			target.AddProgram("acgef (17)");
			target.AddProgram("ehnlfa (19)");
			target.AddProgram("hblnwza (7) -> rhtamt, zwiidh");
			target.AddProgram("igqzqiy (167) -> yuzwdix, ruuerqk");
			target.AddProgram("sydqf (31) -> rpjlb, mjseecw, ohyrn, yzexxy");
			target.AddProgram("xjwvvik (62)");
			target.AddProgram("xhqxyc (74) -> avflv, ovhos");
			target.AddProgram("dvltfhm (54) -> pooon, fagyf, owjjja, vhusoux, whrdhq");
			target.AddProgram("aenrksb (12)");
			target.AddProgram("rqgccu (760) -> qhlslym, cqnlk, dbsbuqp");
			target.AddProgram("euezshv (65)");
			target.AddProgram("juvhkoc (1546) -> yxccn, juaquyw, vsvyj");
			target.AddProgram("jygrpp (17)");
			target.AddProgram("zixgz (15)");
			target.AddProgram("irgkfsa (83) -> syhjziw, kzvbkr, lbgwc");
			target.AddProgram("dqvygcd (14)");
			target.AddProgram("fcbeagx (16)");
			target.AddProgram("ugeucjn (34)");
			target.AddProgram("dwhxnif (88)");
			target.AddProgram("insvmt (18)");
			target.AddProgram("zbjdebj (73) -> dukup, cqxav, ivbrype");
			target.AddProgram("kbyijkc (66)");
			target.AddProgram("qumacc (60)");
			target.AddProgram("dkgsxvj (5) -> hafgurf, qmygary");
			target.AddProgram("zdseqzi (67)");
			target.AddProgram("nsqfu (1724) -> tgvzdov, ksuhtas, arbrp, nbpkmt");
			target.AddProgram("njvsnz (128) -> lztme, txkog, yypfse");
			target.AddProgram("fdurqvg (198) -> trnpdnb, ijlmcnx");
			target.AddProgram("oxcou (13)");
			target.AddProgram("neclo (61)");
			target.AddProgram("wyucu (66)");
			target.AddProgram("lfvih (99) -> rnzpmw, eoxubh, xazpni");
			target.AddProgram("xzndm (199) -> hxlsxdj, csvni, ohapkri");
			target.AddProgram("jwutq (32)");
			target.AddProgram("jldgbkx (87)");
			target.AddProgram("luulwx (57)");
			target.AddProgram("ivxnetm (267) -> zdelwv, ctdghk");
			target.AddProgram("butfc (58) -> nhbff, hbzkf, ytbwqwb");
			target.AddProgram("pmafsug (1041) -> hkmaxza, uryqiso, alhkjxm, pnjgt, nadwsc");
			target.AddProgram("dkcrll (47)");
			target.AddProgram("ccdpnr (72)");
			target.AddProgram("mhvhtg (44)");
			target.AddProgram("icmmx (22)");
			target.AddProgram("pnjgt (55) -> obqblrl, fuvpi");
			target.AddProgram("ytqrut (1468) -> euqxp, ixukpw");
			target.AddProgram("ruzgpq (84)");
			target.AddProgram("blwxqfp (10)");
			target.AddProgram("yyfrmb (15)");
			target.AddProgram("ffcwobn (71)");
			target.AddProgram("uwopuvj (17)");
			target.AddProgram("lmvfuql (20)");
			target.AddProgram("htojdr (72) -> rzaocr, pxncq");
			target.AddProgram("qnblxrh (7) -> qjhdxdr, bhwxgp, dvpay, ktooxbh");
			target.AddProgram("vnlcfxn (42)");
			target.AddProgram("wdwfjh (32)");
			target.AddProgram("tmmwda (70) -> fqyogt, ootknbf");
			target.AddProgram("jiwpf (48)");
			target.AddProgram("ywhmyp (77)");
			target.AddProgram("yptyp (75)");
			target.AddProgram("izuxb (33)");
			target.AddProgram("oustcqz (25)");
			target.AddProgram("wevbhta (63)");
			target.AddProgram("kdwzsz (41)");
			target.AddProgram("flyxei (81)");
			target.AddProgram("lcfsu (18) -> cqdyyoo, sxrzzuy, iqegs, yieehh");
			target.AddProgram("ihimta (44) -> wjyekj, yeimwk");
			target.AddProgram("vurdsd (91)");
			target.AddProgram("icxhhje (80)");
			target.AddProgram("kqtye (46)");
			target.AddProgram("nbpkmt (60) -> thzvetu, qjcsn");

			_output.WriteLine(target.CalculateBottomProgram());
		}
	}
}