using AdventOfCOde;
using FluentAssertions;
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;

namespace AdventOfCodeTest
{
	public class Day2Test
	{
		ITestOutputHelper output;

		public Day2Test(ITestOutputHelper output)
		{
			this.output = output;
		}

		[Fact]
		public void Should1()
		{
			var key = new Day2().Calculate("ULL".ToStringArray());

			key.Should().Be(1);
		}

		[Fact]
		public void Should2()
		{
			var key = new Day2().Calculate("RRDDD".ToStringArray(), 0, 0);

			key.Should().Be(9);
		}

		[Fact]
		public void Should3()
		{
			var key = new Day2().Calculate("LURDL".ToStringArray(), 2, 2);

			key.Should().Be(8);
		}

		[Fact]
		public void Should4()
		{
			var key = new Day2().Calculate("UUUUD".ToStringArray(), 1, 2);

			key.Should().Be(5);
		}



		[Fact]
		public void ShouldSolve()
		{
			var input1 = "LRULLRLDUUUDUDDDRLUDRDLDDLUUDLDDLRDRLDRLLURRULURLDRLDUDURLURRULLDDDUDDRRRDLRRDDLDURDULLRDLLLDRDLLDULDUDLLDLDRUDLLDLDDRRRDRLUDRDDLUDRRDUDUDLLDDUUDLRDUDRRUDUDRULRULUDRUUDLDLULLRLDLDDRULLRLLLULUULDURURLUUULDURLDDDURRUUDURDDDULDLURLRDRURDRUDRLLDLDRUURLLLRDRURUDLRLUDULLDDURLRURDLRDUUURRLULRRLDDULUUURLRRRLLLLLURDDRUULUDRRRUDDLLULRRUULDRDDULRLDDDRRUULUDRLRUDURUUULDLDULUUDURLLLRRDDRDLURDDDLDDDLRDRLDDURLRLLRUDRRLLDDDDDURDURRDDULDULLRULDRUURDRRDUDDUDDDDRRDULDUURDRUDRLDULRULURLLRRDRDRDLUUDRRLRLDULDDLUUUUUURRLRRRULLDDDRLRDRRRRRRRDUUDLLUDURUDDLURRUDL".ToStringArray();
			var input2 = "UDUUURRLRLLDDRRDRRRLDDDLURURLLUDDRLUUDRRRDURRLLRURDLLRRDUUDDDDRDRURRLLLLURDLRRRULLLDLLLUDDLDRRRDLDUUDDRDUDDUURDDLULULDURDURDRUULURURRURDUURUDRRUDRLLLLRRDLLDRDDRLLURDDDUDUDUDRUURDDRUURDLRUUDDRDUURUDDLLUURDLUDRUUDRRDLLUUURDULUULDUUDLLULUUDLUDRUUDUUURLDDDRLRURDDULLRDRULULUDLUUDDDUUDLDUUDRULLDUURDDRUDURULDRDDLRUULRRRDLDLRDULRDDRLLRRLURDLDRUDLRLUDLRLDLDURRUULRLUURDULDRRULLRULRDLLDLDUDRUDDUDLDDURDDDRDLUDRULRUULLRURLDDDRDLRRDRULURULDULRDLDULDURDRDRDRDURDRLUURLRDDLDDRLDDRURLLLURURDULDUDDLLUURDUUUDRUDDRDLDRLRLDURRULDULUUDDLRULDLRRRRDLLDRUUDRLLDLUDUULRDRDLRUUDLRRDDLUULDUULRUDRURLDDDURLRRULURR".ToStringArray();
			var input3 = "LDURLLLRLLLUURLLULDLRLLDLURULRULRDUDLDDUDRLRRDLULLDDULUUULDRLDURURLURLDLRUDULLLULDUURLLRDLUULRULLLULRDRULUDLUUULDDURLUDDUDDRDLDRDRUDLUURDDLULDUULURLUULRDRDLURUDRUDLDRLUUUUULUDUDRRURUDRULDLDRDRLRURUUDRDLULLUDLLRUUDUUDUDLLRRRLDUDDDRDUDLDLLULRDURULLLUDLLRUDDUUDRLDUULLDLUUDUULURURLLULDUULLDLUDUURLURDLUULRRLLRUDRDLLLRRRLDDLUULUURLLDRDLUUULLDUDLLLLURDULLRUDUUULLDLRLDRLLULDUDUDRULLRRLULURUURLRLURRLRRRDDRLUDULURUDRRDLUDDRRDRUDRUDLDDRLRDRRLDDRLLDDDULDLRLDURRRRRULRULLUUULUUUDRRDRDRLLURRRRUULUDDUDDDLDURDRLDLLLLLRDUDLRDRUULU".ToStringArray();
			var input4 = "URURRUUULLLLUURDULULLDLLULRUURRDRRLUULRDDRUDRRDUURDUDRUDDRUULURULDRLDRDDDLDLRLUDDRURULRLRLLLDLRRUDLLLLRLULDLUUDUUDRDLRRULLRDRLRLUUDDRRLLDDRULLLRLLURDLRRRRRLLDDRRDLDULDULLDLULLURURRLULRLRLLLLURDDRDDDUUDRRRDUUDDLRDLDRRLLRURUDUUUDLDUULLLRLURULRULRDRLLLDLDLRDRDLLLRUURDDUDDLULRULDLRULUURLLLRRLLLLLLRUURRLULRUUUDLDUDLLRRDDRUUUURRRDRRDULRDUUDULRRRDUUUUURRDUURRRRLDUDDRURULDDURDDRDLLLRDDURUDLLRURLRRRUDDLULULDUULURLUULRDLRDUDDRUULLLRURLDLRRLUDLULDRLUDDDRURUULLDLRLLLDULUDDRLRULURLRDRRDDLDLURUDDUUURRDDLUDDRDUULRRDLDRLLLULLRULRURULRLULULRDUD".ToStringArray();
			var input5 = "RUDLLUDRRDRRLRURRULRLRDUDLRRLRDDUDRDLRRLLRURRDDLRLLRRURULRUULDUDUULDULDLRLRDLRDLRUURLDRLUDRRDDDRDRRRDDLLLRRLULLRRDDUDULRDRDUURLDLRULULUDLLDRUDUURRUDLLRDRLRRUUUDLDUDRRULLDURRDUDDLRURDLDRLULDDURRLULLRDDDRLURLULDLRUDLURDURRUDULDUUDLLLDDDUUURRRDLLDURRDLULRULULLRDURULLURDRLLRUUDDRRUDRDRRRURUUDLDDRLDRURULDDLLULULURDLDLDULLRLRDLLUUDDUDUDDDDRURLUDUDDDRRUDDLUDULLRDLDLURDDUURDLRLUUDRRULLRDLDDDLDULDUDRDUUULULDULUDLULRLRUULLDURLDULDRDLLDULLLULRLRD".ToStringArray();

			var key1 = new Day2().Calculate(input1);
			var key2 = new Day2().Calculate(input2);
			var key3 = new Day2().Calculate(input3);
			var key4 = new Day2().Calculate(input4);
			var key5 = new Day2().Calculate(input5);

			output.WriteLine($"{key1}{key2}{key3}{key4}{key5}");
			
			var result = $"{key1}{key2}{key3}{key4}{key5}".Should().Be("53255");
		}

		public class Day2BackToBasicsTest
		{
			[Fact]
			public void ShouldUp()
			{
				new Day2().Calculate("U".ToStringArray()).Should().Be(2);
			}

			[Fact]
			public void ShouldRight()
			{
				new Day2().Calculate("R".ToStringArray()).Should().Be(6);
			}

			[Fact]
			public void ShouldDown()
			{
				new Day2().Calculate("D".ToStringArray()).Should().Be(8);
			}


			[Fact]
			public void ShouldLeft()
			{
				new Day2().Calculate("L".ToStringArray()).Should().Be(4);
			}

			[Fact]
			public void ShouldUp2()
			{
				new Day2().Calculate("UU".ToStringArray()).Should().Be(2);
			}

			[Fact]
			public void ShouldRight2()
			{
				new Day2().Calculate("RR".ToStringArray()).Should().Be(6);
			}

			[Fact]
			public void ShouldDown2()
			{
				new Day2().Calculate("DD".ToStringArray()).Should().Be(8);
			}

			[Fact]
			public void ShouldLeft2()
			{
				new Day2().Calculate("LL".ToStringArray()).Should().Be(4);
			}

			[Fact]
			public void ShouldTraverse()
			{
				new Day2().Calculate("UULLDDDDDRRLU".ToStringArray()).Should().Be(5);
			}
		}
	}

	public static class StringExtensions
	{
		public static IEnumerable<string> ToStringArray(this string source)
		{
			return source.ToCharArray().Select(x => x.ToString());
		}
	}
}
